### ISSUE TITLE
Erra无法拦截本地请求吗？

### ISSUE THREAD

**Issue by xiewangmei** [hughfenghen/erra#3]

**Comment by hughfenghen** [comment]
Erra是一个代理服务，需要做一些配置让本地请求通过Erra转发。

如果想拦截非浏览器发出的请求，可以配置操作系统默认代理设置为：http://127.0.0.1:3344  
如果想拦截浏览器中发出的localhost请求，因为switchomega有个bug 无法代理localhost域名的请求，可以通过修改hosts文件解决。参考这个issue ：https://github.com/FelisCatus/SwitchyOmega/issues/1712#issuecomment-565323980
